Add custom scss theme colors to bootstrap
KappaSigmaMu/ksm-app pull request #1
Opened 2021-07-06 00:05 UTC by lkinas

This PR modifies some theme colors of bootstrap. 
Maybe it adds a dark theme and light theme too, 
maybe it's too early for that ¯\_(ツ)_/¯

2021-07-06 13:37 UTC, murilooon approved these changes

2021-07-08 23:07 UTC, lkinas commented
@murilooon real que eu acho que era só isso msm rs
acho que a parte de light/dark theme vem depois né, o que vc acha?

2021-07-11 19:23 UTC, murilooon commented
> @murilooon real que eu acho que era só isso msm rs
> acho que a parte de light/dark theme vem depois né, o que vc acha?

Yes, I think this can be done later.

PS: Will we have dark/light mode?

2021-07-11 19:30 UTC, murilooon requested changes
:nail_care:

2021-07-11 19:30 UTC, murilooon commented on src/index.scss
> +  "light": #eee,
```suggestion
  'primary': #e6007a,
  'success': #0dd27f,
  'cian': #00ffe1,
  'dark': #212529,
  'grey-dark': #2d2d2d,
  'light': #eee,
```

2021-07-11 21:58 UTC, lkinas commented
> > @murilooon real que eu acho que era só isso msm rs
> > acho que a parte de light/dark theme vem depois né, o que vc acha?
> 
> Yes, I think this can be done later.
> 
> PS: Will we have dark/light mode?

@murilooon I will bring that up with Gus, we can decide this later.

2021-07-11 22:20 UTC, murilooon approved these changes

2021-07-11 22:21 UTC, merged