Account selector refactor
KappaSigmaMu/ksm-app pull request #20
Opened 2021-08-26 02:04 UTC by danielSbastos

Hey,

In this PR I change the manner in which the account is fetched. Now, instead of being in the reducer/dispatch, it is done via a useEffect hook.

The current selected account is now accessible to the parent component App, meaning that any of the children can have access to it if necessary.

2021-08-29 23:31 UTC, laurogripa requested changes
Let's fix this warnings

2021-08-30 13:21 UTC, alfakini commented on src/components/Navbar.tsx
> +const NavbarAccount = ({ setAccount, account }: any) => {
Aways name the components with it's "type" as the end word.

```suggestion
const AccountNavbar = ({ setAccount, account }: any) => {
```

2021-08-30 13:53 UTC, alfakini commented on src/components/AccountSelector.tsx
> +  const [accountSelected, setAccountSelected] = useState(initialAddress)
```suggestion
  const [selectedAccount, setSelectedAccount] = useState(initialAddress)
```

2021-08-30 13:53 UTC, alfakini commented on src/components/AccountSelector.tsx
> +  initialAddress: string
```suggestion
  activeAccountAddress: string
```

2021-08-30 13:53 UTC, alfakini commented on src/components/Navbar.tsx
> +  setAccount: (account: string) => void
```suggestion
  setActiveAccount: (account: string) => void
```

2021-08-30 13:53 UTC, alfakini commented on src/components/Navbar.tsx
> +  setAccount,
```suggestion
  setActiveAccount,
```

2021-08-30 13:53 UTC, alfakini commented on src/components/Navbar.tsx
> +  account,
```suggestion
  activeAccount,
```

2021-08-30 13:53 UTC, alfakini commented on src/components/Navbar.tsx
> +            <NavbarAccount setActiveAccount={setAccount} account={account} />
```suggestion
            <NavbarAccount setActiveAccount={setActiveAccount} activeAccount={activeAccount} />
```

2021-08-30 13:53 UTC, alfakini commented on src/components/Navbar.tsx
> +  account,
```suggestion
  activeAccount,
```

2021-08-30 13:53 UTC, alfakini commented on src/components/Navbar.tsx
> +  account: string
```suggestion
  setActiveAccount: (activeAccount: string) => void
  activeAccount: string
```

2021-08-30 13:53 UTC, alfakini commented on src/components/Navbar.tsx
> +          setAccountAddress={setActiveAccount}
```suggestion
          activeAccount={activeAccount}
          setActiveAccount={setActiveAccount}
```

2021-08-30 13:53 UTC, alfakini commented on src/helpers/fetchAccounts.ts
> +  setAccountAddress: (account: string) => void,
```suggestion
  setActiveAccount: (activeAccount: string) => void,
```

2021-08-30 13:53 UTC, alfakini commented on src/helpers/fetchAccounts.ts
> +      setAccountAddress(accounts[0].address)
```suggestion
      setActiveAccount(accounts[0].address)
```

2021-08-30 13:53 UTC, alfakini commented on src/pages/App.tsx
> +  const [account, setAccount] = useState<string>('')
```suggestion
  const [activeAccount, setActiveAccount] = useState<string>('')
```

2021-08-30 13:53 UTC, alfakini commented on src/pages/App.tsx
> +          <Home account={account} setAccount={setAccount} />
```suggestion
          <Home activeAccount={activeAccount} setActiveAccount={setActiveAccount} />
```

2021-08-30 13:53 UTC, alfakini commented on src/pages/Home.tsx
> +  account,
```suggestion
  setActiveAccount,
  activeAccount,
```

2021-08-30 13:53 UTC, alfakini commented on src/pages/Home.tsx
> +  account: string
```suggestion
  setActiveAccount: (activeAccount: string) => void
  activeAccount: string
```

2021-08-30 13:53 UTC, alfakini commented on src/pages/Home.tsx
> +        account={account}
```suggestion
        setActiveAccount ={setActiveAccount}
        activeAccount ={activeAccount}
```

2021-08-30 14:00 UTC, alfakini commented on src/components/Navbar.tsx
> +  account: string
```suggestion
  activeAccount: string
```

2021-08-30 14:00 UTC, alfakini commented on src/components/Navbar.tsx
> +            <AccountNavbar setActiveAccount={setAccount} account={account} />
```suggestion
            <AccountNavbar setActiveAccount={setAccount} activeAccount={activeAccount} />
```

2021-08-30 14:00 UTC, alfakini commented on src/components/Navbar.tsx
> +          setAccountAddress={setActiveAccount}
```suggestion
          activeAddress={activeAddress}
          setActiveAccount={setActiveAccount}
```

2021-08-30 15:27 UTC, alfakini approved these changes

2021-08-30 22:25 UTC, murilooon approved these changes

2021-08-30 22:26 UTC, merged