Add Bids page
KappaSigmaMu/ksm-app pull request #29
Opened 2021-09-28 00:22 UTC by alfakini

In this PR, we introduce the Bids page. It is the starting point for the pages related to the human journey.
In the following PRs, the components will be generalized.

<img width="1368" alt="Screen Shot 2021-09-27 at 21 19 45" src="https://user-images.githubusercontent.com/4171/135002390-8f4b13ea-cf47-4d98-92c3-b4f661d7df03.png">

2021-09-28 17:56 UTC, alfakini commented
![](https://github.trello.services/images/mini-trello-icon.png) [[PAGE] Create page Bids/List as human](https://trello.com/c/MMGLvBOq/207-page-create-page-bids-list-as-human)

2021-09-29 22:46 UTC, murilooon commented on src/pages/App.tsx
> +          </Route>
After merging https://github.com/KappaSigmaMu/ksm-app/pull/30 this Route will need to be updated

2021-09-29 22:48 UTC, murilooon commented on src/pages/human/Bids/Page.tsx
> +    })
```suggestion
    if (api) {
      api.query.society.bids().then((response: Vec<PalletSocietyBid>) => {
        setBids(response)
      })
    }
```

WDYT?

2021-09-29 22:49 UTC, murilooon commented on src/components/Sidebar.tsx
> +      style={{ color: '#707070', fontSize: 16, lineHeight: 2, fontWeight: 700, textDecoration: 'none' }}
I think we can use Styled Components here and get the color from global, WDYT?

2021-09-29 22:51 UTC, murilooon commented on src/components/BidsList.tsx
> +      </Row> */}
Something happen here?

2021-09-29 22:51 UTC, murilooon commented on src/components/BidsList.tsx
> +    style={{ color: '#fff', lineHeight: 3, marginTop: 5, backgroundColor: '#343A40', borderRadius: 6 }}
Styled Components

2021-09-29 22:51 UTC, murilooon commented on src/components/BidsList.tsx
> +  <Row style={{ color: '#fff', lineHeight: 3 }}>
Styled Components

2021-09-29 22:52 UTC, murilooon commented on src/components/BidsList.tsx
> +    <Col xs={2} className="text-end" style={{ paddingRight: 36 }}>Value</Col>
Styled Components

2021-09-29 22:52 UTC, murilooon commented on src/components/BidsList.tsx
> +    <Col xs={2} className="text-end" style={{ paddingRight: 36 }}>
Styled Components - could use the same styled component as other above

2021-09-29 22:56 UTC, murilooon requested changes
Pointed some nits. Also, this PR will need to be updated before merging.

2021-09-30 19:09 UTC, murilooon approved these changes

2021-10-02 13:21 UTC, merged

2021-10-02 13:33 UTC, alfakini commented
![](https://github.trello.services/images/mini-trello-icon.png) [[PAGE] Implement the Bids Lists page](https://trello.com/c/JEUF7Iik/180-page-implement-the-bids-lists-page)